import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Rubik } from "@next/font/google";
import { Header } from "@/components/Header";

const rubik = Rubik({ subsets: ["latin"] });
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "EduGate",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body
				className={`${rubik.className} ${geistMono.variable} antialiased`}
			>
				<Header />
				<main className="mx-12">{children}</main>
			</body>
		</html>
	);
}
